# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Train_Your_Eyes_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Train_Your_Eyes_iOS
  pod 'NewPopMenu', '~> 2.0'
  
  target 'Train_Your_Eyes_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Train_Your_Eyes_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
